export const ACTION_ADD_COUNTER = 'ADD_COUNTER';
export const ACTION_DELETE_COUNTER = 'DELETE_COUNTER';
export const ACTION_INCREMENT = 'INCREMENT';
export const ACTION_DECREMENT = 'DECREMENT';
export const ACTION_RESET_COUNTER = 'RESET_COUNTER';
export const ACTION_RESET_ALL_COUNTERS = 'RESET_ALL_COUNTERS';
export const ACTION_INCREASE_RANGE = 'INCREASE_RANGE';
export const ACTION_DECREASE_RANGE = 'DECREASE_RANGE';